### ISSUE TITLE
error on installation

### ISSUE THREAD

**Issue by mimidbe** [Lenty/SLiCAP_python#40]
hello, 
i have an on installation with conda:
```
>python setup.py install --user
running install
..
..
..
..
The Maxima path found is: C:\maxima-5.47.0\bin\maxima.bat
Succesfully ran Maxima command
Acquiring LTSpice Command
LTSpice command set as: C:\Program Files\LTC\LTspiceXVII\XVIIx64.exe
Found the LTSpice directory:  C:\Program Files\LTC\LTspiceXVII\XVIIx64.exe
SLiCAP version: 1.6.0
ERROR: could not set install location.
Generating the configuration file
Found template file:  SLiCAPtemplate.py
Traceback (most recent call last):
  File "C:\SLiCAP\setup.py", line 222, in <module>
    setuptools.setup(
  File "C:\Anaconda3\envs\pytorch\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\Anaconda3\envs\pytorch\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "C:\Anaconda3\envs\pytorch\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Anaconda3\envs\pytorch\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Anaconda3\envs\pytorch\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "C:\Anaconda3\envs\pytorch\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\SLiCAP\setup.py", line 48, in run
    self._gen_config_file()
  File "C:\SLiCAP\setup.py", line 170, in _gen_config_file
    txt = txt.replace("$DOCPATH", self._doc_location)
TypeError: replace() argument 2 must be str, not None
>
```
the installation was attempted on windows 10. 
thank you in advance for your answer.

**Comment by antonmontagne** [comment]
I can't reproduce this error. Can you upgrade Python in Anaconda, and try to re-install it?
